apiVersion: v1
kind: Service
metadata:
  name: card-management-service
spec:
  type: NodePort
  selector:
    app: card-management
  ports:
    - port: 5010
      targetPort: 5010
      nodePort: 30510